Table User {
  id varchar(30) [pk]
  email varchar(255) [unique, not null]
  name varchar(255) [not null]
  password varchar(255) [not null]
  created_at timestamp [default: `now()`]
  updated_at timestamp [default: `now()`]
}

Table Category {
  id varchar(30) [pk]
  name varchar(100) [unique, not null]
  description varchar(500)
  created_at timestamp [default: `now()`]
}

Table Product {
  id varchar(30) [pk]
  sku varchar(50) [unique, not null]
  name varchar(255) [not null]
  description text
  unit_price bigint [not null]
  currency varchar(3) [default: 'NGN', not null]
  stock_level int [default: 0, not null]
  created_at timestamp [default: `now()`]
  updated_at timestamp [default: `now()`]
  created_by varchar(30) [not null]
  category_id varchar(30) [not null]
}

Table Cart {
  id varchar(30) [pk]
  created_at timestamp [default: `now()`]
  updated_at timestamp [default: `now()`]
  created_by varchar(30) [not null]
}

Table CartItem {
  id varchar(30) [pk]
  quantity int [not null, default: 1]
  created_at timestamp [default: `now()`]
  updated_at timestamp [default: `now()`]
  cart_id varchar(30) [not null]
  product_id varchar(30) [not null]
  
  indexes {
    (cart_id, product_id) [unique]
  }
}

Ref: Product.created_by > User.id
Ref: Product.category_id > Category.id
Ref: Cart.created_by > User.id
Ref: CartItem.cart_id > Cart.id
Ref: CartItem.product_id > Product.id